import Head from "next/head";
import { Inter } from "next/font/google";
// I am gonna to use this for my main styling for future
import styles from "@/styles/Home.module.css";

//This will be used by form
import { useForm } from "react-hook-form";
import { useEffect, useState } from "react";
import { Button } from "react-bootstrap";
import StarsComponent from "@/components/stars";
import Router from "next/router";

const inter = Inter({ subsets: ["cyrillic"] });

export default function Form() {
    const [isSubmitted, setIsSubmitted] = useState(false);
    const [formData, setData] = useState({});
    const { Player1, Player2 } = formData;

    const { register, handleSubmit, setValue } = useForm({
        defaultValues: {
            Player1: "",
            Player2: "",
        },
    });

    function submitForm(data) {
        setData(data);
        setIsSubmitted(true);
    }

    function pushToGame() {
        Router.push({
            pathname: "/game",
            query: {
                Player1: Player1, 
                Player2: Player2,
            },
        });
    }

    useEffect(()=>{
        if (isSubmitted) {
            pushToGame();
        }
    },[isSubmitted])

    return (
        <>
            <StarsComponent />
            <Head>
                <title>Tic Tac Toe</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1 , maximum-scale=1"
                />
            </Head>

            {isSubmitted ? (
                <>
                    {/* {pushToGame()} */}
                    {/* <Game
                        Player1={Player1}
                        Player2={Player2}
                        setIsSubmitted={setIsSubmitted}
                        setValue={setValue}
                    ></Game> */}
                </>
            ) : (
                <div className={styles.formContainer}>
                    <form onSubmit={handleSubmit(submitForm)}>
                        <div className={"touchAnimation"}>
                            Player 1 :{" "}
                            <input {...register("Player1")} required></input>
                        </div>
                        <br />

                        <div className={"touchAnimation"}>
                            Player 2 :{" "}
                            <input {...register("Player2")} required></input>
                        </div>
                        <br />

                        <div className={styles.playButton}>
                            <Button type="submit">Play</Button>
                        </div>
                        <br />
                    </form>
                </div>
            )}
        </>
    );
}
